# Generated by Django 4.2.1 on 2023-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResinProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='craft/images')),
            ],
        ),
    ]
